@startuml

title Concept Classes

Class "Користувач"
Class "Список поетичної\n літератури"
Class "Поетична література"

"Користувач""1" -> "1""Список поетичної\n літератури" : отримує
"Список поетичної\n літератури""1" o-- "*""Поетична література"
"Користувач""1" -> "*""Поетична література" : отримує

@enduml