@startuml uml2

title Deployment for information System
left to right direction

node "<< Смартфон >>" as sm {
	node "<< ОС Android >>" {
	       node "<< Веб-навігатор >>" {
                       component [~*.apk\n(Android Studio)]
               }
	}
}

interface Touch_screen
interface Microphone
Touch_screen  -- sm
Microphone -- sm

@enduml
