@startuml
title Activity Diagram 

start
:Користувач вводить назву поетичного твору;
if (Результати пошуку знайдено?) then (Yes)
  :Отримано список \nпоетичної літератури \nу відповідності до запиту;
else (No)
  :Помилка, даних не існує!;
endif
stop

@enduml